### ISSUE TITLE
nits to fix and complete the TODO section

### ISSUE THREAD

**Issue by inesrob** [roll-wg/draft-ietf-roll-enrollment-priority#1]
Source: https://mailarchive.ietf.org/arch/msg/roll/lIF2yWQNHmKn7nDJwyFyy1x7p9k

---------- Forwarded message ---------
From: Georgios Z. Papadopoulos <georgios.papadopoulos@imt-atlantique.fr>

Hello Ines,
I have observed very few typos and one comment : 
- time-slotted channel hopping (TSCH) —> Time-Slotted Channel Hopping (TSCH)- (the "pledge)” —> (the “pledge”)- "6LRs that see this DIO Option SHOULD increment the minimum priority if they observe congestion on the channel used for join traffic.”GP: channel here, I suppose it is ment the radio channel. Then between node A and B link, we have 16 radio channels.Thus, in stead saying … congestion on the channel, we could have … congestion on the link (or subnetwork)?- Finally, I am not sure if the standard should be written as 802.15.4 or IEEE 802.15.4.

----------------------------------------------------------------------

 this should be solved : 
Section 2 : “(TODO: how much?  Do we need to standardize this?)”

**Comment by mcr** [comment]
I have validated that I applied these comments.
