### ISSUE TITLE
should priority have more than 1 bit: join disabled/enabled?

### ISSUE THREAD

**Issue by mcr** [roll-wg/draft-ietf-roll-enrollment-priority#10]
Rahul> The Root should have the ability to send any value into the DODAG. If
Rahul> Root is limited to value 0/1 and if it is not possible for any 6LRs to
Rahul> update the value then we might as well restrict the parameter size to
Rahul> 1 bit! Am I missing anything here?

A goal here is to allow a device which is re-attaching to be able to judge
between several equivalent DODAGs which might be on different PANIDs, with
different capacities.   0/1 might not be enough here, and I'd prefer to err
on the side of creating a slider which we never use in the end.

**Comment by inesrob** [comment]
Version 10 solves this issue
