### ISSUE TITLE
what EB and priority, if any should a node with no feasible parent emit?

### ISSUE THREAD

**Issue by mcr** [roll-wg/draft-ietf-roll-enrollment-priority#11]
Pascal> A node that does not have a feasible parent should poison or
Pascal> detach. It does not make sense for a detached node to take
Pascal> visitors. So probably it should beacon a join priority of 0x7F.

Does detach mean to send a DIO with infinite rank?
I'm undecided if it should send a beacon at all.

**Comment by inesrob** [comment]
Version 10 solves this issue
