### ISSUE TITLE
should root explicitedly reset trickle timer?

### ISSUE THREAD

**Issue by mcr** [roll-wg/draft-ietf-roll-enrollment-priority#12]
should the enrollment priority option include an explicit flag to reset trickle timer?
or should it be implicit when changing to/from 0x7f?
should this flag be an explicit other option?

**Comment by pthubert** [comment]
I agree that the option does not reset trickle but a new DIO flag does. And the root may use it here..


A bientôt;

Pascal

**Comment by mcr** [comment]
A new DIO option will be created called "TrickleReset" which the root can include at it's discretion.

**Comment by pthubert** [comment]
Michael there’s a flag field in the DIO base object. Isn’t it enough to pick one?


A bientôt;

Pascal

**Comment by mcr** [comment]
You are suggesting we take a bit from the flags to mean reset.  I agree that's a good idea.

**Comment by pthubert** [comment]
Exactly :)


A bientôt;

Pascal

**Comment by inesrob** [comment]
Version 10 solves this issue
