### ISSUE TITLE
add explicit lollipop counter into enrollment priority option

### ISSUE THREAD

**Issue by mcr** [roll-wg/draft-ietf-roll-enrollment-priority#13]
in order to recognize changes to the option vs lost packets vs restarts of a 6LR, add a lollipop counter.
4 bits ought to enough? 0-12?

**Comment by pthubert** [comment]
I suggest one byte that behaves exactly per section 7. Same code less text.


A bientôt;

Pascal

**Comment by inesrob** [comment]
Version 10 solves this issue

**Comment by inesrob** [comment]
Version 10 solves this issue
