### ISSUE TITLE
-05 Section 3.1, questions

### ISSUE THREAD

**Issue by dbarthel-ol** [roll-wg/draft-ietf-roll-enrollment-priority#7]
In Section 3.1, I read "other parts of the DODAG tree". This looks odd, is it a DAG or is it a tree? The RPL DODAG can subsume in a tree, but in general doesn't.
In Section 3.1 as well, I read "In addition, an operator would be unable to turn off enrollment traffic by sending a maximum value enrollment priority to the sub-tree". It's unclear to me what part of the text "In addition"refers to. Besides, in which situation could sending a maximum value enrollment priority *not* turn off enrollment traffic? My understanding is that the enrollment priority can only be increaded down the DODAG.

**Comment by inesrob** [comment]
Version 10 solves this issue
